### ISSUE TITLE
Members need to return their ETH balance and GEN balance too

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#105]
Should come from subgraph: https://github.com/daostack/subgraph/issues/113

**Comment by jellegerbrandy** [comment]
Eth will not be returned by the subgraph (bc of graph node limitations) - we'll need to get that from the blockchain using the `arc.getBalance(address)` observable. 

(thinking of renaming that function to `ethBalance` so it is more explicit)

**Comment by jellegerbrandy** [comment]
and in any case, the "members" collection is just for reputation holders of the dao - so we cannot use that for the profile page, which should work also for non-reputation-having users. 

For the gen, you can use `arc.GENToken().balanceOf(address)`
