### ISSUE TITLE
proposal.winningOutcome has wrong type

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#141]
proposal.winningOutcome says it is a ProposalOutcome enum type, but actually it is a string containing either "Pass" or "Fail". Either the type needs to be changed on IProposalState or we need to convert it to a ProposalOutcome, which to me is preferable since we use ProposalOutcome values everywhere else.

**Comment by tibetsprague** [comment]
@jellegerbrandy what do you think? could use a quick turn around on this one

**Comment by jellegerbrandy** [comment]
ProposalOutcome it is. I'll do this now.
