### ISSUE TITLE
Helper function to return # GEN staked on currently open proposals for a DAO

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#162]

**Comment by tibetsprague** [comment]
We may not need anything more from the subgraph for now, but there is a conversation here: https://github.com/daostack/subgraph/issues/168

**Comment by jellegerbrandy** [comment]
If we implement somwthing likw this we want a more generic solution, whcih also provides answers to questions such as "how much have i staked in total and how much of that is redeemable" or "how much was staked in genericscheme proposals in the past year"

**Comment by jellegerbrandy** [comment]
closing this because (a) inactivity and (b) if we want these kidn of statistics, we should not calculate them in the client but in the subgraph.
