### ISSUE TITLE
Make it possible to interact with different chains in different environments

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#174]
We sometimes need to be able to test on Rinkeby or even main net locally since some bugs only show up on those chains. It would be sweet if we could just change chains in MetaMask and whatever environment you're in would work with that chain. Is that possible?

**Comment by jellegerbrandy** [comment]
In alchemy, we already have that behavior, so I am not sure what you mean. Closing this, plz reopen if I misunderstood.

**Comment by tibetsprague** [comment]
this is not true, locally if you switch to Rinkeby it does not load the data from Rinkeby nor let you interact with Rinkeby. it complains that you are not using ganache

**Comment by jellegerbrandy** [comment]
True, you are right. We have `npm run start-staging`, we can add an `npm run start-production`. In alchemy :-)

**Comment by tibetsprague** [comment]
ugh, you're right, sorry to not figure that out myself...
