### ISSUE TITLE
consider using subgraph version for all subversions (graph-node,migration..)

### ISSUE THREAD

**Issue by orenyodfat** [daostack/client#177]
the current solution where the docker-compose.yml pull specific versions is not optimal and might be a place for mistake as it need to be manually edited

**Comment by jellegerbrandy** [comment]
The only solution i see is to somehow generate the docker-compose files. But that is just a lot of code for keepign two lines in sync, and not worth the trouble I think.  
in any case, the docker-compose files are used only for testing, and if mistakes are made, they are made by devs, and should be caught in the tests immediately, so there is no serious problem here, just an inconvenience.
