### ISSUE TITLE
define externaltokenBalance on dao object

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#179]
in `src/dao.ts`, there is a TODO.

**Comment by jellegerbrandy** [comment]
perhaps this is nto needed at all int he API, see https://github.com/daostack/alchemy/issues/635

**Comment by tibetsprague** [comment]
I don't think we need this anymore, do we still want/need to associate DAOs with a specific external token that they will use for rewards? like a default? @A-Zak
