### ISSUE TITLE
Threshold calculations seem wrong

### ISSUE THREAD

**Issue by A-Zak** [daostack/client#183]

**Comment by A-Zak** [comment]
@tibetsprague you had some examples :)

**Comment by tibetsprague** [comment]
example: https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0x2153577cb7f7d0ef463f5eb836ad747787e9a56e8b6d73d764c744b37fa2c5b9

mousing over the proposal card doesnt show any GEN to boost, if you click staking it says -0.1 GEN to boost! but it is not boosted. so, whats going on...?

**Comment by jellegerbrandy** [comment]
Not excluding that the calculations are wrong, but the way that you describe it, it looks like it is a frontend issue, and unfortunately the state is now very different...  can you provide another example?

**Comment by jellegerbrandy** [comment]
so was this a rounding error in the UX after all? Closing this, plz re-open if still relevant..
