### ISSUE TITLE
Default account is not really changing the account in the tests

### ISSUE THREAD

**Issue by leviadam** [daostack/client#185]
Whe using the `web3.eth.accounts.defaultAccount = ...` notion. It does not really change where the TX is sent from, as far as I can see checking graphiQL.

Example:
https://github.com/daostack/client/blob/d25b5acb0228be58d325c9b90d895c0eda1d7c18/test/proposal-execute.spec.ts#L60

**Comment by jellegerbrandy** [comment]
it is in fact a useless line and is removed in  https://github.com/daostack/client/pull/232
