### ISSUE TITLE
Every time a proposal state changes update all other proposal thresholds in the queue

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#189]
When a proposal is boosted we need to update all the other proposals GEN to boost or unboost amounts. Not sure if this should happen in the client or subgraph...

**Comment by tibetsprague** [comment]
I guess in the subgraph

**Comment by jellegerbrandy** [comment]
The threshold logic is currently being refactored in the subgraph, so we can wait for that.

**Comment by jellegerbrandy** [comment]
This should be fixed in `0.1.16`
