### ISSUE TITLE
Use lower case addresses everywhere

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#193]
I keep running into issues where something is broken because addresses are not matching when in fact they should because sometimes they are lower case and sometimes not.

For example the scheme objects have lower case addresses but the contractAddresses are upper case.

**Comment by jellegerbrandy** [comment]
ok this is a good point. I thiknk we should prefer to use the checksummed addresses everywhere, which is safer when users copy them (i.e. with the capital latters)

**Comment by tibetsprague** [comment]
but what if someone gives us a lower cased one? maybe we just need a compare function that is case insensitive
