### ISSUE TITLE
Need a better way to determine the scheme a proposal came from

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#195]
In alchemy i need to be able to easily query a proposal's parent scheme name. Right now a proposal has a "type", but there are two types for SchemeRegistrar, which is confusing. Why do we need SchemeRegistrarProposeToRemove as a separate proposal type? In alchemy we care mostly about which scheme the proposal is in, and we can use secondary info to determine if its a remove scheme proposal or add scheme proposal. So can type change to just be the scheme name? Or if not, ca we also have a second field called proposal.scheme that just returns the scheme name?

**Comment by tibetsprague** [comment]
actually, wait, we do need to now from the proposal if it is a remove or add/edit too... so both pieces of info would be useful.

**Comment by jellegerbrandy** [comment]
+1 for adding the scheme name.

So my idea was that the `proposalType` would be the way that the proposal "commands" a certain UX. So we would have a separate type for each of the GenericAction proposals (that we know about) that a user can do in alchemy, and 3 types of actions for the schemeregistrat (add, edit, delete). (i realize there are only two now). Let's discuss this in the next call?

**Comment by tibetsprague** [comment]
yeah sounds good to me
