### ISSUE TITLE
Do not get all `members` just to get the memberCount

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#20]
In line https://github.com/daostack/client/blob/master/src/dao.ts#L62, we use `dao.members.length` to count the members. This fetches all members, and is not scaleable. Does graphql have some kind of `count` functinality?

**Comment by ben-kaufman** [comment]
I don't think GraphQL supports that. We can add that to the subgraph though. Do you think that would be good enough?

**Comment by jellegerbrandy** [comment]
yes, definitely
