### ISSUE TITLE
Should EntityClass.search(...) Always Return Observable<EntityClass[]>

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#213]
Currently there is an inconsistency in the client library where the `.search(...)` static method returns in some cases a collection of state data ([example](https://github.com/daostack/client/blob/27d866b8f48ea7d7dff99c25ff3f3bb34434286b/src/reward.ts#L44)), and in other cases a collection of entity class instances ([example](https://github.com/daostack/client/blob/27d866b8f48ea7d7dff99c25ff3f3bb34434286b/src/proposal.ts#L301)).

From a user of the library's perspective, this causes an inconsistency in usage pattern which makes using the interface cumbersome.

I think this may have been done by design, and may not be an oversight. For example, the `Reward` class does not have any additional functionality that would be exposed through class instance methods, so a class instance wouldn't be preferred in this case.

Would you agree with establishing a new design standard that says that all `EntityClass.search(...)` methods should return `EntityClass[]` collections?

If you agree, I would volunteer to make the necessary updates to the code as this is of particular interest to how DAOcomponents is using the library.

**Comment by jellegerbrandy** [comment]
Yes, I agree.

**Comment by dOrgJelli** [comment]
Awesome, I'll work on this update ASAP (probably this week Thursday).

**Comment by dOrgJelli** [comment]
Didn't have a chance to get to this, will be at a hackathon all weekend, will work on this Monday at the soonest.

**Comment by dOrgJelli** [comment]
Apologies for the lag on this, looking at this now, will post updates.
