### ISSUE TITLE
Support BigNumber Query Options

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#227]
Support BigNumber query option types for EntityClass.search(...) methods. This would, for example, enable querying all members who have "greater than 400 reputation".

This can be done by creating a new type that wraps the number property and the corresponding suffix:
```typescript
interface BigNumberQuery {
  propertyName: string
  propertyValue: number
  suffix: "gt" | "lt" | "gte" | "lte"
}
```
![image](https://user-images.githubusercontent.com/5522128/58388380-11d9b300-7fec-11e9-975f-f8aff7622102.png)

**Comment by jellegerbrandy** [comment]
Looks like a good idea. 
Afaics, to "supporting" all these options is simply a matter of allowing these values as keys in `IXXXQueryOptions`.

(I do not how you want to do  the "BigNumberQuery" type)

**Comment by jellegerbrandy** [comment]
(before https://github.com/daostack/client/issues/217 was resolved we were actually "supporting" all these query options)

**Comment by jellegerbrandy** [comment]
I re-insted the `[id: string]: any` in the query types, so we can pass any argument, as a quick but flexible solution - seemed better then copying over all the types from the graph...
