### ISSUE TITLE
Future-Proofed Proposal Paradigm (Subgraph & Client)

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#229]
Currently, all different types of proposals are being added to a single Proposal EntityClass in the Client library. This will not scale well. Have there already been talks around this issue and are there already some future plans in place?

I propose that a possible solution could include:
- **subgraph**: Use GraphQL interfaces, and have all proposal types (ex: ContributionRewardProposal) implement this interface. Command data could include `title` & `description`.
- **client**: Use class inheritance, where the base class has a `type: string` property and query methods that grabs all the common data. The derived classes would override the query methods to grab the other type specific data. This would allow clients to show a list of all proposals (regardless of type), and show specialized interfaces for proposals they have knowledge of (ex: ContributionRewardProposal => ContributionRewardProposalView).

**Comment by jellegerbrandy** [comment]
Yes, we are aware of the issue, and https://github.com/daostack/client/pull/225 is a start towards that refactor (there, the code for the different schemes it in its own file).. It uses more of a plugin-like pattern (so it follows neither of your suggestions), but it is not very structured.

**Comment by jellegerbrandy** [comment]
I am closing this, but the point remains valid :-)
