### ISSUE TITLE
Dont have a default proposal type in proposal.search?

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#230]
Right now if you don't pass a type into Proposal.search it sets type to ContributionReward. But what if you want get all proposals regardless of type, as we do for the history page? Seems like if you dont pass in a type it should return all proposal types

**Comment by tibetsprague** [comment]
actually i think this is necessary because otherwise i have to track and search for every known proposal type in Alchemy separately for the history page

**Comment by tibetsprague** [comment]
as is I also have to search for SchemeRegistrarAdd, SchemeRegistrarEdit and SchemeRegistrarRemove separately which is a lot of code

**Comment by jellegerbrandy** [comment]
it is so on current master and will arrive in alchemy with PR https://github.com/daostack/alchemy/pull/755
