### ISSUE TITLE
Standardize on EntityClass.constructor(id, context)

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#234]
The DAOcomponents project hit a breaking change when updating to the latest client version. The error came from the Proposal entity's constructor:
https://github.com/daostack/client/blob/a22b0aab663f57b566ea24d7cae815072502f1d8/src/proposal.ts#L227

The introduction of additional construction parameters seems unnecessary, as a GraphQL entity can be queried by just knowing its `id`. Additional information can be queried there after, or set manually if already known.

A work around (that didn't work) was to use the `dao.proposal(id)` method, but this is not synchronous so it causes a break as these EntityClasses are being constructed within the render method.

I propose that the following standards be adopted:
1. Construction of an EntityClass is always synchronous and only requires the `id` and `context` to be filled out.
2. Additional required information for the usage of the EntityClass (ex: contract addresses) are either manually set by the user, or queried from the subgraph. If the user of the library hasn't done either, and tries to use a method that requires this "core" data, an error is thrown saying something along the lines of "missing core data, please either provide this after construction or call the `fetchCoreData` method".

Your thoughts?

**Comment by dOrgJelli** [comment]
@jellegerbrandy would love to hear your thoughts on this.

**Comment by jellegerbrandy** [comment]
After talking with @dOrgJelli , we decided that indeed it would indeed be best to follow this pattern.

**Comment by jellegerbrandy** [comment]
hey @dOrgJelli I've been working on this but there is a problem/drawback to the pattern. 

Take for example: `Scheme(id, context)`. The `id` argument of the constructor is not something that is available on-chain - which means that to create a Scheme instance, you _must_ pass through the subgraph.

While this makes sense in some use case, I'd stil like to be able to do most transactions without having subgraph support. i.e. the client lib must be able to create a proposal having only access ot the scheme and dao address. 

I am not completely sure how to handle this, yet, but perhaps we can overload the constructor argument, so we can do **both**:

`new Scheme(id, context)`

`new Scheme({dao: '0x124', address: '0x1245, params: '0x12344' }, context)`

**Comment by jellegerbrandy** [comment]
Or perhaps the general pattern could be:

`new Entity(opts, context)`

Where `opts` may provide just the `id` - but does not always _have_ to.

**Comment by jellegerbrandy** [comment]
After reconsidering the question with @dOrgJelli :

Premiss:
* DAOComponents likes to have anice clean uniform interface for the entities, of the form `Entity(id, context)`
* on chain transactions should be possible to do without depending on the subgraph, i.e. by providing the data that we need to construct the transation manually.hese data (contractAddresses, mostly) typically do not change in the lifetime of the Entity (i.e. the scheme address is always the same) and need only to be set once.  Currently this is done by providing these data in the Entity constructors, i.e. `new Scheme(daoAvatarAddress, ....); scheme.createProposal(....)` T

The proposal is to be able to do use both patterns, by overloading the constructor, and adding to each entity the methods `fetchStaticData` (fetches immutable data from subgraph and caches them), and `setStaticData` to set these data manually. 

So the entity class looks like this:

```
interface IStaticOptions {
   ...
}

class Entity {
   constructor(idOrOpts: string|IStaticOpts, context: Arc)

   fetchStaticData(): IStaticOpts {
   // fetch the static data from the blockchain and set them   
}
   setStaticData(opts: IStaticOpts) {

   }
}
```
}

**Comment by dOrgJelli** [comment]
Thank you so much @jellegerbrandy for making this a priority of yours, I know this was a lot of work, you're the best!
