### ISSUE TITLE
Support the ReputationFromToken Scheme

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#278]
See https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=feature/1320/silent and https://github.com/daostack/subgraph/issues/294 

We will also need a function call to do the redeem on the contract

**Comment by jellegerbrandy** [comment]
https://github.com/daostack/alchemy/issues/965
