### ISSUE TITLE
DAOcomponents Needs Consistent Subgraph Endpoint

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#287]
DAOcomponents continues to become broken when the subgraph endpoint changes, for example from v23 to v24.

How do you propose we remedy this issue? Here are some possible solutions:
* DAOcomponents host its own subgraph. This subgraph would run a version that's compatible with the version of the client library that DAOcomponents is currently using.
* DAOstack has a "service lifetime agreement" that states that all versions of the subgraph, once live, will be kept up for a minimum of 2 months.

**Comment by dOrgJelli** [comment]
I view this as a high priority issue, as users of DAOstack's client library (and the subgraph) can be broken overnight.

**Comment by dOrgJelli** [comment]
@jellegerbrandy @orenyodfat really interested in hearing a response to this, as DAOcomponents is something I don't know if we should recommend people take a dependency on knowing their app could become broken at any point the endpoint is changed.

**Comment by jellegerbrandy** [comment]
Sorry about the absurdly late reply. This is indeed an important point. I've opened an issue in the subgraph repo for this, where it is more likely that oren will follow up on it: https://github.com/daostack/subgraph/issues/321

**Comment by dOrgJelli** [comment]
No worries @jellegerbrandy!
