### ISSUE TITLE
Every query to the subgraph updates every single subscription

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#288]
At least this is what I think im seeing. In Alchemy whenever any new subscription is created or old one updates, every single subscription created anywhere in the app thinks it has new data and updates/renders. I think this is what is causing a lot of slowness in the app and making tests time out

**Comment by dkent600** [comment]
Does this turn out to be just in Alchemy, or is there something also happening in the client?  @tibetsprague

**Comment by jellegerbrandy** [comment]
alchemy
