### ISSUE TITLE
Member ID Refinement

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#291]
Prerequisite information: Member.id is created like so `keccak256(concat(repContract, memberAddr))`.

In the following example:
```typescript
const member = new Member({ memberAddr, daoAddr }, context);
await member.fetchStaticState();

// is null
member.id
```
Member.id is null. This is because the constructor is being given the DAO's address and the member's address, which completely satisfy the static state, so `fetch...` does nothing.

I propose that the following fix be implemented:
- use "reputation address" instead of "dao address" in the constructor, and calculate the id client side using `keccak`.

Ideally, the standard would be:
- once the constructor is called, the user can be assured that the id will be set.

This would mean that IDs are always easily assignable (id = address) or easily derivable through static data (id = keccak(contract, holder)), but with Stake and Vote this isn't currently possible as they use the event's id.

**Comment by jellegerbrandy** [comment]
This is a good point, and will als  help with caching. I'll wait for https://github.com/daostack/subgraph/issues/325 before implementing this, though.

**Comment by jellegerbrandy** [comment]
MemberId is calculated using member address and reputationcontracdt address (not the DAO address);  for the rest it is done as described
