### ISSUE TITLE
support additional subscription callbacks for subgraph v27 (graph-node 14.0.0).

### ISSUE THREAD

**Issue by orenyodfat** [daostack/client#294]
see https://github.com/graphprotocol/graph-node/pull/1062

**Comment by jellegerbrandy** [comment]
I am not sure what you are referring to here  @orenyodfat

**Comment by orenyodfat** [comment]
once you subscribe there is a default dummy event in the source stream , which the client should ignore.
see graphprotocol/graph-node#1062 .

see how it is handled in the subgraph test . https://github.com/daostack/subgraph/blob/master/test/0.0.1-rc.16/Subscription.spec.ts#L97 
though maybe Apollo just managed with that...

**Comment by jellegerbrandy** [comment]
all tests pass, so I think there is no issue
