### ISSUE TITLE
Implement subscription pattern that returns the current result immediately

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#3]
We want (for example)  `arc.daos()` to call `onNext(resultSet)` immediately with the current results, and then again every time the resultSet changes.

The stand graphql subscription behavior is (I think) that a query such as 
`subscription { daos { id }}` will only yield a new resultSet once the set of proposals changes. i.e. we do not get the first result, as we want.

One way to implement this is to hav `arc.daos()` first to a http query for the crurent result set, return that, and then open a websocket to listen for changes. (This is not very elegant, and we will need to take care to not miss changes that occur between getting the current resutl and opening the websocket, but if we cannto think of anything better it will do)

**Comment by tsuberim** [comment]
If you're worried about missing updates while request is in flight you can do both in parallel. But I think this is negligible.

**Comment by jellegerbrandy** [comment]
@ben-kaufman suggests we might want to use https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.watchQuery

**Comment by tsuberim** [comment]
@jellegerbrandy @ben-kaufman This `watchQuery` is not what we want. It doesn't listen to websocket subscriptions. It just allows you to be notified whenever an entity is updated by a regular http query.

**Comment by jellegerbrandy** [comment]
This is implemented with the pattern here: https://github.com/daostack/client/blob/dev/src/arc.ts#L55

Closing this issue, but if you guys want to have a quick look that would be useful, as myplan is to re-use this pattern as well
