### ISSUE TITLE
`sendTransaction` Handle "Error: Transaction was not mined within 50 blocks..."

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#319]
Currently `sendTransaction` doesn't handle the case where web3.js' retries exceeds 50 tries. You can read more about this issue here:
ethereum/web3.js#1102

**Comment by jellegerbrandy** [comment]
sorry for the late reply. It is not clear to me what the action required is here. The web3js issue you refer to was closed for quite a while.
