### ISSUE TITLE
strings should not be declared as number

### ISSUE THREAD

**Issue by dkent600** [daostack/client#329]
I find that WEI properties in places like Token and Reputation are being declared as `number`, when they are in fact `string`.  This is disconcerting because if they were actually `number` then we would be having problems at execution time.

**Comment by jellegerbrandy** [comment]
the policy is: all token amount representations are BN instances, all counters and such as Numbers, and all the rest are strings.

this is indeed wrong in the `totalSupply` of the IReputationSTate, which is declared a number (should be BN) but returned as a string. 

But I do not see the same in the Token - can you point me to where you see this behavior?

**Comment by dkent600** [comment]
@jellegerbrandy 

> But I do not see the same in the Token - can you point me to where you see this behavior?

If you search for "number"  you'll see a lot of lines like this:

```
.then((balance: number)
```

**Comment by jellegerbrandy** [comment]
ah, you are right, and I had misunderstood. Thanks!
