### ISSUE TITLE
return more scheme data in the proposal.state()

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#340]
from https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1596/silent:
```The problem here is that client is explicitly populating the proposal.scheme as only a partial ISchemeState, missing all of the scheme-specific params properties. Since we often (always?) need to know the name of the scheme when working with a proposal, can we make the client return a full scheme state for proposals?```

**Comment by dkent600** [comment]
This is high priority for the Competitions stuff.

**Comment by jellegerbrandy** [comment]
So as far as I can see, `proposalstate.scheme.name` is arleady populated, I added tests to prove that:

https://github.com/daostack/client/blob/competition/test/proposal.spec.ts#L234

The name of the "Competition Scheme" at the moment is `ContributionRewardExt` - this should be `Competition`, so I'm leaving this issue open to address that:
https://github.com/daostack/client/blob/competition/test/proposal-competition.spec.ts#L194

**Comment by dkent600** [comment]
What is missing are the scheme *params* props such as `genericSchemeParams`, `contributionRewardParams`, or `contributionRewardExtParams`, etc.

**Comment by jellegerbrandy** [comment]
Ok, I'll add the params.
