### ISSUE TITLE
competition issues to address

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#349]
These are issues that @dkent600 reaised in discord [to be divided up in separate issues when necessary]

- [ ] Would be nice if ICompetitionSuggestion contained the vote and votes methods.  I guess this is an effect of how the client lib entities are architected in general, where entity's static and dynamic properties are stored in class fields rather than the class itself, whereas the entity methods are stored elsewhere in the class.  This is awkward for the user to code and not intuitive as it does not follow the usual object-oriented design pattern everyone is used-to.
- [ ] The lack of function return value typing and use of 'any' makes it harder to figure out what you're doing in places like the test code.  Take this code, for example:

const receipt2 = await competition.createSuggestion(suggestion2Options).send()
const suggestion2 = receipt2.result

No idea what are the types of receipt2 and suggestion2.  intellisense won't tell you and there are no comments in the code to make up for it.

So I see the test code but still have no easy way to understand what is going on without digging deeper into the code.   (I'm not asking you to tell me, rather just to hear my feedback on the coding practice.)

- [ ] In public vote(): Operation<CompetitionVote>  why get the dynamic state and not just fetch the static state?
ICompetitionSuggestion is used for both static and dynamic state, though it contains dynamic fields totalVotes, redeemedAt  and rewardPercentage.
 

- [ ] I am finding a use for isCompetitionScheme, and it seems efficient.  Would it make sense to export it from the client (it is not in index.d.ts)?

- [ ] is there a way for the client to tell me if a solution is a winning solution? I'll be wanting to think about how to do this efficiently, with an easy-to-use result set, for all suggestions at once on a given proposal.

- [ ] re: getting the collection of votes-per-suggestion, effectively a "join" on suggestions and votes.  I need to figure how to do that with the client lib when the CompetitionSuggestion state doesn't include a votes property that the lib would populate as part of setting the state.  I'm thinking of populating my own property on the entity, locally in Alchemy.
 
- [ ] re: static and dynamic state in CompetitionSuggestion.  I find it quite confused.
Looking at Competition.suggestions().  It is defined to return CompetitionSuggestion[].
CompetitionSuggestion is defined to contain three properties, id, suggestionId? and staticState?.

I think you may already realize this:  It actually can contain much more than that.  Competition.suggestions() invokes CompetitionSuggestion.search() which, via mapItemToObject results in returning an object that contains the full complement of properties in ICompetitionSuggestion, which with the current code is (mistakenly) the equivalent of both static state and dynamic state.

Yet these properties are hidden from the consumer of Competition.suggestions() because the return value CompetitionSuggestion[] doesn't declare them.

Moreover, after having retrieved all these (hidden) properties in CompetitionSuggestion, its value of staticState remains undefined.
 
- [ ] 
Further, when I invoke Competition.suggestions() I am getting back CompetitionSuggestions that don't contain the method fetchStaticState.  So the only way I currently have to obtain the desired properties is a hack that casts the CompetitionSuggestion to ICompetitionSuggestion
 
- [ ] Looks like ICompetitionSuggestionQueryOptions isn't being exported (index.ts)
 
- [ ] I think ICompetitionSuggestionQueryOptions.proposal should be removed.  It should always come from Competition.id.  It doesn't make sense to instantiate Competition with id 0x1 only to obtain suggestions from Competition id 0x1.  In any case, I note that you are always overriding it even if the caller provides it.  So again no point in having it in ICompetitionSuggestionQueryOptions.
 
- [ ] Same thing with  removing suggestion from ICompetitionVoteQueryOptions used by CompetitionSuggestion.votes.  It should always come from CompetitionSuggestion

Except that CompetitionSuggestion.votes has a further issue.  What if the caller provides competition?  Then you shouldn't be overriding suggestion because the presumption is that the caller wants all votes in the competition, not just for the suggestion.  In this case, seems like votes should be part of Competition, not CompetitionSuggestion.

I'd say we need two votes methods, one in each place.

At any rate, if indeed it won't work to pass competition alone, then I have only a more difficult way of counting votes, by enumerating suggestions.
 
- [ ] Can you change this:` redeemedAt: secondSinceEpochToDate(item.redeemedAt)` 
to return null or undefined when the item has not been redeemed?
 
- [ ] I am expecting the following to automatically update after the user votes (note subscribe is set to true):

submission.votes({ where: { voter: voterAddress, suggestion: submissionId} }, { subscribe, fetchAllData: false })
    .pipe(map((votes: Array<CompetitionVote>) => !!votes.length), first());

But it doesn't appear to be updating.  Do you have any idea offhand why this would be?

**Comment by dkent600** [comment]
Closing as these have all been moved to separate tickets
