### ISSUE TITLE
dynamic and static state in ICompetitionSuggestion are confused 

### ISSUE THREAD

**Issue by dkent600** [daostack/client#354]
in `public vote(): Operation<CompetitionVote>` why get the dynamic state and not just fetch the static state?

`ICompetitionSuggestion` is used for both static and dynamic state, though it contains dynamic fields `totalVotes`, `redeemedAt`  and `rewardPercentage`.

**Comment by jellegerbrandy** [comment]
Yes you are right, this was a quick programming shortcut. This is not strictly speaking a bug, and the idea is that in a next client version, we will drop the distinction between static and dynamic states anyway. So I'm closing this as "wontfix" unless this leads to problems upstream (in which case, plz reopen)
