### ISSUE TITLE
can't obtain all votes for a competition

### ISSUE THREAD

**Issue by dkent600** [daostack/client#357]
In `CompetitionSuggestion.votes`, what if the caller provides `competition` as an option?  The code is always setting `suggestion` (see https://github.com/daostack/client/issues/356). which is a mistake because in this case the caller wants all votes in the competition, not just for the one suggestion.

Perhaps we need two places to get votes, one in `CompetitionSuggestion` and one in `Competition`.

**Comment by jellegerbrandy** [comment]
So all "search" functions in the client are implemeted using the following pattern:

Tehre is a static method on the Entity class that sets no default params and searches in the entire set, which is where the query logic is implemented:

`EntityClass.search(arc, options, apolloQueryOptions)`

So we have:

`Proposal.search(arc ,...)`
`CompetitionSuggetsion.search(arc, ...)`


Then we have a number of convenience methods on class insntances that  call tehse class methods:

`scheme.proposals(..)` will call `Proposal.search(...)` with the scheme.id set
`comeptitionSuggestion.votes(...)`  will call `CompetitionVote.search(...) with the suggestionid set

So if you want to search in the whole set, you can always use `CompetitionVote.search(arc, ...)`

Given this info, it if is useful to have `Competition.votes`, I can easily implement that. Is it useful?

**Comment by dkent600** [comment]
one in `CompetitionSuggestion` and one in `Competition` sounds good.

**Comment by jellegerbrandy** [comment]
Actually, the `competitionSuggestion.votes(...)` behavior is as intended and I do not think it should change. The idea is that htis will always give you the "votes of the suggestion", just like `competiion.votes(...)` will give you all the votes of the competition.

**Comment by dkent600** [comment]
Referring to the use case I described in the description, where one supplies `competition` as an ICompetitionVoteQueryOptions` option.

The intent of that option should be the receive all the votes in a competition.  But as the client code is written, that will not be possible.  Thus the API of this function is misleading and will not operate as advertised.  In any case, it makes only little to no sense to allow anyone to use a `CompetitionSuggestion` class to obtain all the votes in a competition, even if the code worked. So I think `CompetitionSuggestion.votes` should take a different options object interface, not `ICompetitionVoteQueryOptions`.

On the face (I haven't tested yet), `ICompetitionVoteQueryOptions` looks OK for `CompetitionVote.search(arc, ...)`.

**Comment by dkent600** [comment]
@jellegerbrandy Bigger problem:  looks like `CompetitionVote.search(arc, { competition: "0x12345" })` crashes.  Subgraph is expecting "proposal", not "competition".

**Comment by jellegerbrandy** [comment]
a fix for the bug is coming up.

About the interface: yes you are right. The interface is really only good for the static search (i.e. `CompetitionVote.search(...)`. I am re-using that interface for `competition.votes(...)` and `suggestion.votes(...)`, and it would be more correct to define seperate interfaces for these cases that remove the options that are are not being used. 

I decided against that a long way back, because I thought it would lead to way too many interfaces. But as it leads to confusion, perhaps I should reconsider... 

Re: your particular use case: if you want all votes of a compeittion, you should use `competition.votes(...)`, not `suggestion.votes(...)`

**Comment by dkent600** [comment]
I agree to reconsidering  :-)

**Comment by dkent600** [comment]
there is no `competition.votes(...)`, only `CompetitionVote.search(...)`.  Would be nice and consistent to have the former.
