### ISSUE TITLE
submission.votes is not updating

### ISSUE THREAD

**Issue by dkent600** [daostack/client#359]
I am expecting the following to automatically update after the user votes (note subscribe is set to true):

```
submission.votes({ where: { voter: voterAddress, suggestion: submissionId} }, { subscribe, fetchAllData: false })
    .pipe(map((votes: Array<CompetitionVote>) => !!votes.length), first());
```

But it doesn't appear to be updating.  Do you have any idea offhand why this would be?

**Comment by jellegerbrandy** [comment]
The `first()` operator will give you the first result, and then close the subscription. So this seems correct behavior...

(please re-open if I misunderstood)

**Comment by dkent600** [comment]
problem for me is that certain queries never return (hang) unless I do a `first()`.  Still trying to understand the best way to work around that.  Suggestions welcome!

**Comment by dkent600** [comment]
Yay!  I finally figured out a pattern that works:

An example: 

```
const proposals = dao.proposals({ }, { subscribe: true })
  .pipe(
    // work on each array individually so that toArray can perceive closure on the stream of items in the array
    mergeMap(proposals => of(proposals).pipe(
      mergeMap(proposals => proposals),
      mergeMap(proposal => proposal.state().pipe(first())),
      filter((proposal: IProposalState) => proposal.winningOutcome === IProposalOutcome.Pass ),
      toArray())
    )
  );
```
