### ISSUE TITLE
subscriptions fail unpredictably after a while

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#36]
Steps to reproduce:

On one shell:
`docker-compose up graph-node`

In oanther shell:

- `npm run setup-env`
- `for run in {1..10}; do npm run test -- test/client.spec.ts; done`

on my machine, the test fails after the second or third time, and does not recover.

running the test manually with some interval seems to make the break occur later.

(this happens in commit #88b125e9c69f45308143de876985b2b37656aef3)

**Comment by orenyodfat** [comment]
Does the client.spec.ts test unsubscribe at the end ?
It has jest 5000 ms timeout .. what happened if it wait more than 5000 ms to the subscription?

**Comment by jellegerbrandy** [comment]
This should be fixed in the new graph-node image
