### ISSUE TITLE
need to make sure we can redeem

### ISSUE THREAD

**Issue by dkent600** [daostack/client#361]
Implement redemptions.  Here is what I see:

1)  It looks like before anyone can successfully redeem on a Competition suggestion, someone must first have done a redeem on the original ContributionRewardExt.  Doing so effectively frees up the Competition suggestion rewards.  Until then, the winners can receive nothing.  The Competitions UI should be made to handle this case gracefully.

2) the ContributionRewardExt redeem must be done on the `Rewarder` contract using a different function (`contributionRewardExtRedeem`) than we use for regular ContributionReward proposals.. 

3) if the avatar lacks funds at the time of redeeming on `ContributionRewardExt`, then either eth or external token rewards will not be freed up.  If a winner then tries to redeem on a suggestion, they will receive only a partial reward.  The app needs to somehow know this and feedback to the user in the same manner that we do with regular proposal redemptions.

**Comment by jellegerbrandy** [comment]
Both 1 and 3 are Alchemy issues with which the client can help little.

Regarding 2, the `competition` branch and version `0.2.38-experimental-4`: `proposal.claimRewards` already calls `contributionRewardExtRedeem`.

**Comment by jellegerbrandy** [comment]
Here is the relevant line in the test: https://github.com/daostack/client/blob/competition/test/proposal-competition.spec.ts#L221
