### ISSUE TITLE
Suggestions with 0 votes should not be considered winners

### ISSUE THREAD

**Issue by dkent600** [daostack/client#368]
I'm seeing suggestions being marked as winners even though they have zero votes (when there is an insufficient # of submissions having votes).  Suggestions with 0 votes should not be considered winners.

**Comment by jellegerbrandy** [comment]
I've added this test to confirm that it works: https://github.com/daostack/client/pull/375/files#diff-c4af85d71d3af3e7fafb628727795f47R531
