### ISSUE TITLE
isWinner is returning true even though voting has not yet begun

### ISSUE THREAD

**Issue by dkent600** [daostack/client#371]
I'm not sure is this is a bug or not:  `isWinner()` is returning true even though the voting period has not yet even begun, much less ended.

Is this intentional?

**Comment by dkent600** [comment]
My feeling is this behavior is best, and should be up to the consumer to decide what they want to do with it.

**Comment by jellegerbrandy** [comment]
yes, this is intentional, and it seems you like this behavior as well, so let' skeep it.
