### ISSUE TITLE
Not all suggestions should be winners

### ISSUE THREAD

**Issue by dkent600** [daostack/client#376]
Not all suggestions should be marked winners in this competition on staging:

https://alchemy-staging-rinkeb-pr-1280.herokuapp.com/dao/0xfa0646b726ba94840eb3cd77095d46da775ad3ed/crx/proposal/0xb2ee8e9d30db6b0d65bd472f4c0c9e1684f98b8a2b837143ed1c63d944aad86c

**Comment by jellegerbrandy** [comment]
This seems a subgraph issue: https://github.com/daostack/subgraph/issues/441

**Comment by jellegerbrandy** [comment]
should be fixd with new subgraph release
