### ISSUE TITLE
suggestion vote should succeed

### ISSUE THREAD

**Issue by dkent600** [daostack/client#378]
On staging, when I try to vote on a submission, I see "Transaction Sent" but then nothing happens, no confirmation.

Then if I try to vote again, there is an error:  
![image](https://user-images.githubusercontent.com/1821666/72349220-17365b80-36aa-11ea-9c6e-4872badc40d2.png)

Problem is occurring here:

https://alchemy-staging-rinkeb-pr-1280.herokuapp.com/dao/0xfa0646b726ba94840eb3cd77095d46da775ad3ed/crx/proposal/0xb0aee0b4abf0471bac3e14fc31aa5133ef2b84676e2e2e3a642d720e4f11ece7/competition/submission/0x1d55a9cdab2d6d554e2f2c98826e7a5fd0b5272e6b99df7f0da73ec68022fe05

Transaction record that never got mined:  https://rinkeby.etherscan.io/tx/0x2098edc5fd9e2541a2497a1beb62f581838eb00c72e50874fd6d999565c7aaab

Maybe rinkeby is misbehaving right now?

**Comment by jellegerbrandy** [comment]
This is not a bug. If you look at the rinkeby transaction you can see that it failed because of "already voted on this suggestion". 

We do however need more informative errors from the client, so I created #379 (so  instead of "trasnaction failed :-(" you'll see "already voted on this suggestion")

**Comment by dkent600** [comment]
It was a rinkeby slowdown.  What actually happened here is:

1. voted once, nothing happened
2. voted again, nothing happened
3. #1 [finally succeeded](https://rinkeby.etherscan.io/tx/0x490f3a01ed309bb4779cd3532c3754a88d978d26607b9f83d6a1e21e1db762d7)
4. #2 [finally failed](https://rinkeby.etherscan.io/tx/0x2098edc5fd9e2541a2497a1beb62f581838eb00c72e50874fd6d999565c7aaab)
