### ISSUE TITLE
There should be no rewards left on the CrExt after all submissions are redeemed

### ISSUE THREAD

**Issue by dkent600** [daostack/client#380]
Forgive me I haven't thoroughly investigated this:  Alchemy insists on feeding back on the ProposalDetails page that the beneficiary is owed whatever rewards it is owed on the Crext proposal, even after everything has been redeemed on the winning submission(s).  There should be no more rewards left on the CrExt.  I'm wondering if there is a subgraph or client issue there?

**Comment by jellegerbrandy** [comment]
Can you point me to an example? Can we reproduce this on staging?

**Comment by dkent600** [comment]
Yes, on staging:  https://alchemy-staging-rinkeb-pr-1280.herokuapp.com/dao/0xfa0646b726ba94840eb3cd77095d46da775ad3ed/proposal/0x2a1139bf714e9383488a7a3aa3f1671a57d32942f8db026fd9460106a7fb3515

**Comment by jellegerbrandy** [comment]
Ok, I made this subgraph issue: https://github.com/daostack/subgraph/issues/446

**Comment by jellegerbrandy** [comment]
the link is broken, so I cannot ccheck the end result, but this should be fixed
