### ISSUE TITLE
Need a better way to get all actually redeemable rewards for a proposal

### ISSUE THREAD

**Issue by tibetsprague** [daostack/client#395]
Right now the logic to get Redeemable rewards in Alchemy is super messy and continues to have bugs. What we really need is for the subgraph and/or client to be able to tell us exactly what rewards are redeemable for a proposal at any given moment (and ideally why they are not if they are not). The latest bug is we are showing ContributionRewards as redeemable even if they are in an ExpiredFromQueue proposal if the proposal is executed and had more winning votes than losing. I am trying to fix in alchemy but actually it's hard to completely remove the proposal from the Redeem Menu because it is pulling "Redeemable Proposals" directly from the client and the client doesn't include this logic. Not sure if this work should be in the client or the subgraph.

**Comment by tibetsprague** [comment]
The result is we end up with menu items in the Redeem Menu that can never be redeemed

**Comment by tibetsprague** [comment]
I created this: https://github.com/daostack/subgraph/issues/455

**Comment by jellegerbrandy** [comment]
this fix should come with client 0.2.54, which is currently in PR in alchemy
