### ISSUE TITLE
Enable efficient competition caching

### ISSUE THREAD

**Issue by dkent600** [daostack/client#405]
See this that describes what is needed:  https://github.com/daostack/alchemy/issues/1370#issuecomment-582580182

**Comment by jellegerbrandy** [comment]
- [x] (new Competition(proposalId)).suggestions()
- [ ] (new Competition(proposalId)).votes()
- [ ] (new CompetitionSuggestion(suggestionId)).votes()

**Comment by jellegerbrandy** [comment]
done in #406 , will be included in next release 0.2.59
