### ISSUE TITLE
Rename Package to "arc.js"

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/client#417]

**Comment by tibetsprague** [comment]
hehe, this would bring us full circle. there may be some code from the old arc.js we still want? maybe somehow we can archive that in an accessible way

**Comment by dOrgJelli** [comment]
@tibetsprague the old arc.js has not been updated in > 1 year, and I don't think there is any intention to maintain it going forward. I propose we:
- Rename arc.js to arc.js-deprecated
- Archive it on GitHub
- Rename client to arc.js

**Comment by dOrgJelli** [comment]
@tibetsprague @jellegerbrandy @dkent600 @orenyodfat do you all feel comfortable with going ahead and renaming this repository to arc.js?

NOTE: The old URL will be automatically forwarded to the new URL by GitHub, so all existing links to https://github.com/daostack/client will work.

**Comment by dOrgJelli** [comment]
@tibetsprague @jellegerbrandy would one of you like to rename this repo? I do not have perms.

**Comment by dOrgJelli** [comment]
Closing and continuing here: https://github.com/daostack/client/issues/448
