### ISSUE TITLE
Tooling for checking service status

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#5]
The library needs some functionality to check the status of different services. 

Could perhaps look like this:
```js
const arc = new Arc({ graphqlHttpProvoder: 'http://this.url/here', .... })
console.log(await arc.serviceStatus())
\\ prints:
\\ { graphSqlHttpProvider: { status: 'down'}
\\    web3Provider: { status: 'up', 'perhaps': 'moreinfo' }
\\ 
```
This would be useful both on the client side (i.e. a "status" screen in alchemy), but especially, now, for devs, i.e. to have an npm script so we can do something like `npm run check-dev-system-status`

**Comment by tsuberim** [comment]
This needs to be a part of the client lib?

**Comment by ben-kaufman** [comment]
I think it's good to have it here as it can be very useful for developing and using the library.

**Comment by jellegerbrandy** [comment]
here's a rudimentary script in the alchemy repo: https://github.com/daostack/alchemy/blob/client-integration/scripts/serviceStatus.js
