### ISSUE TITLE
use BigNumber for all balance values

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#73]

**Comment by tibetsprague** [comment]
also make sure all numbers are being converted to and from WEI correctly, right now the numbers we are getting in Alchemy are too big and probably need to be converted from WEI

**Comment by jellegerbrandy** [comment]
I think all numbers should be in their original base values (i.e. "wei") always, and should only be converted to decimal numbers at the last moment in the UI

**Comment by tibetsprague** [comment]
this seems pretty important right now, I may start working on it

**Comment by jellegerbrandy** [comment]
merged the  PR. Thanks @tibetsprague
