### ISSUE TITLE
get dao constants like thresholdConst

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/client#87]
cf. https://github.com/daostack/subgraph/issues/43

**Comment by jellegerbrandy** [comment]
opened a subgraph issue: https://github.com/daostack/subgraph/issues/100

**Comment by tibetsprague** [comment]
Also the client should cache the dao.numBoostedProposals, since that is the other number Alchemy needs to calculate the num GEN to boost any individual proposal

**Comment by tibetsprague** [comment]
although maybe the client always needs to subscribe to the boosted proposals list since this value could change all the time

**Comment by jellegerbrandy** [comment]
Ok, instead I think the sbugraph should just index the "thresholdToBoost" after all, so we do nto need to calculate it client side.  So you'd just get it from `proposalState.thresholdToBoost`. I'll update the issue on the subgraph.

**Comment by jellegerbrandy** [comment]
thresholdConst is now part of the dao state, and the "thresholdtoBoost" issue will be resolved in #103
